config/routes.rb
Rails.application.routes.draw do
    root 'pages#index'
    
 resources :pages  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @pages = Page.all 
  end

  def show
    @page = Page.find(params[:id])
  end

  def new
    @page = Page.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Blog Pages</h1>
<% @pages.each do |page| %>
    <h2><%= page.title %></h2>
    <%= link_to 'Show', page_path(page) %>
<% end %>

app/views/pages/new.html.erb
<h1>Create New Page</h1>
<%= form_for @page do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br />
  <%= f.label :author %>
  <%= f.text_field :author %>
  <br />
  <%= f.label :body %>
  <%= f.text_area :body %>
  <br />
  <%= f.submit %>
<% end %>

app/views/pages/show.html.erb
<h1><%= @page.title %></h1>
<h4><%= @page.author %></h4>
<p><%= @page.body %></p>
<%= link_to 'Back', pages_path %>